{% set name = "gulp-cli" %}
{% set version = "3.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 683fa88d8d15b49a8adf760f25e4e46f068f1e065fe234e1199b27fe6bf0376e

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - gulp --help

about:
  home: https://github.com/gulpjs/gulp-cli
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Command Line Interface for gulp

extra:
  recipe-maintainers:
    - xhochy
