{% set name = "gulp-cli" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: f90ba044fd1486dcc0f5e7ec07aba39fc62079cd0f3df78f2ba123b404f8094b

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - gulp --help

about:
  home: https://github.com/gulpjs/gulp-cli
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Command Line Interface for gulp

extra:
  recipe-maintainers:
    - xhochy
